### ISSUE TITLE
Cannot use third party models

### ISSUE THREAD

**Issue by adfayed** [langchain-ai/langchain-ibm#11]
Instantiating the WatsonxLLM using:
```
model = WatsonxLLM(model_id = meta-llama/llama-3-1-8b-instruct,
                               params = self.default_params,
                               url = self.credentials["url"],
                               apikey = self.credentials["apikey"],
                               project_id = self.project_id)
```
Generating a response using:
`model.watsonx_model.generate(prompt=user_message, params=self.default_params)`

Output:
`{'model_id': 'meta-llama/llama-3-405b-instruct', 'model_version': '3.1.0', 'created_at': '2024-08-12T18:41:32.047Z', 'results': [{'generated_text': '.', 'generated_token_count': 2, 'input_token_count': 1480, 'stop_reason': 'stop_sequence'}], 'system': {'warnings': [{'message': 'This model is a Non-IBM Product governed by a third-party license that may impose use restrictions and other obligations. By using this model you agree to its terms as identified in the following URL.', 'id': 'disclaimer_warning', 'more_info': 'https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/fm-models.html?context=wx'}]}}`

There is no info/documentation anywhere (should be included in the return warning message) on how or where I can accept the license to proceed and get generated text besides a single dot ".".

**Comment by MateuszOssGit** [comment]
Hi @adfayed 
Sorry for lack in response for 3 weeks. 
Answering on your question, related no info/documentation. Using model you are informed that `By using this model you agree to its terms as identified in the following URL.` Url is provided in `more_info` param. You can open it, filtr by model and get information you need. (About license too)

Could you please provide your `user_message` which you have sent in generate method? It will be helpful for us to better understanding the reason you get such response.

**Comment by MateuszOssGit** [comment]
Due to answer: 
```
Using model you are informed that By using this model you agree to its terms as identified in the following URL. Url is provided in more_info param. You can open it, filtr by model and get information you need. (About license too)
```
Closing the issue.

@adfayed If you have still question please re-open issue.
