### ISSUE TITLE
Using llama-3.1-70B (langchain-ibm version==0.3.0)

### ISSUE THREAD

**Issue by shaigrt** [langchain-ai/langchain-ibm#30]
Hi,

I tested the new langchain-ibm version, it works good for mistral-large.

However with llama-3.1-70B I got the following error: 
```
ibm_watsonx_ai.wml_client_error.ApiRequestFailure: Failure during generate. (POST https://us-south.ml.cloud.ibm.com/ml/v1/text/chat?version=2024-10-01)
Status code: 400, body: {"errors":[{"code":"model_no_support_for_function","message":"Model 'meta-llama/llama-3-1-70b-instruct' does not support function 'function_text_chat'","more_info":"https://cloud.ibm.com/apidocs/watsonx-ai"}],"trace":"99fd521a142a1beebb9cfa4f0fee61f5","status_code":400}
```

Is there a plan to support this model as well?

**Comment by MateuszOssGit** [comment]
Hi @shaigrt 
Yes, there is a plan to support model `meta-llama/llama-3-1-70b-instruct` as well in near future. Our backend service working on it.
Right now we recommend using `mistralai/mistral-large`

**Comment by alonh** [comment]
hi @MateuszOssGit 
Is there an ETA for when additional models will be supported? Thanks.

**Comment by MateuszOssGit** [comment]
@alonh Model `meta-llama/llama-3-1-70b-instruct` should be supported right now.

Right now we support below models for function calling
```python
[
  'ibm/granite-3-2b-instruct',
  'ibm/granite-3-8b-instruct',
  'meta-llama/llama-3-1-70b-instruct',
  'meta-llama/llama-3-1-8b-instruct',
  'meta-llama/llama-3-2-11b-vision-instruct',
  'meta-llama/llama-3-2-1b-instruct',
  'meta-llama/llama-3-2-3b-instruct',
  'meta-llama/llama-3-2-90b-vision-instruct',
  'meta-llama/llama-3-405b-instruct',
  'mistralai/mistral-large'
]
```
